configfile: "config/config.yaml"

##################################################################
##                      Steps in Pipeline                       ##
##################################################################
#   Steps:
#   1) Convert BAM to SAM
#   2) Create TAG directory
#   3) HOMER peak calling
#   4) Process HOMER peaks
#   5) Merge peaks

##################################################################
##                       Glob variables                         ##
##################################################################
import shutil
import glob
import os
import pandas as pd

bam_dir = glob.glob(f"{config['project']}/ChEC-Seq_Analysis-*/results/alignment/scer")[0]
samplescsv = glob.glob(f"{config['project']}/ChEC-Seq_Analysis-*/config/samples.csv")[0]

df = pd.read_csv(samplescsv)
merge_group = df['merge_group'].tolist()

##################################################################
##                          Rule all                            ##
##################################################################
rule all:
    input:
        expand("results/homer_peaks_merged/{group}.bed", group=merge_group)

##################################################################
##                        BAM to SAM                            ##
##################################################################
rule bam2sam:
    input:
        bam = "{bam_dir}/{group}_{rep}.bam",
    output:
        sam = "results/sam/{group}_{rep}.sam"
    log:
        "logs/bam_to_sam/{group}_{rep}.log"
    shell:
        """
        samtools view {input.bam} > {output.sam} 2> {log}
        """

##################################################################
##                    Create Tag directories                    ##
##################################################################
rule homer_tags:
    input:
        sam = "results/sam/{group}_{rep}.sam"
    output:
        tag_dir = directory("results/seq_tags/{group}_{rep}")
    params:
        keepAll = config["homer_params"]["keepAll"]
    log:
        "logs/make_tag/{group}_{rep}.log"
    shell:
        """
        echo "Creating TAG directory for {wildcards.group}_{wildcards.rep}.."
        makeTagDirectory {output.tag_dir} {input.sam} -keepAll {params.keepAll} 2> {log}
        """

##################################################################
##                         Peak calling                         ##
##################################################################
rule peak_calling:
    input:
        tag_dir = "results/seq_tags/{group}_{rep}"
    output:
        homer_peaks = "results/homer_peaks/{group}_{rep}.bed"
    params:
        control = config["control_tags"],
        style = config["homer_params"]["style"],
        size = config["homer_params"]["size"],
        C = config["homer_params"]["C"],
        L = config["homer_params"]["L"],
        F = config["homer_params"]["F"]
    log:
        "logs/peak_calling/{group}_{rep}.log"
    shell:
        """
            findPeaks {input.tag_dir} \
                -style {params.style} \
                -size {params.size} \
                -i {params.control} \
                -o auto \
                -C {params.C} \
                -L {params.L} \
                -F {params.F} \
                2>> {log}
        
        # Homer generates files in tag_dir, copy it to corresponding peak directory
        cp {input.tag_dir}/peaks.txt {output.homer_peaks}
        echo "Called peaks for {wildcards.group}_{wildcards.rep} and saved to {output.homer_peaks}" 
        """

##################################################################
##                    Process peaks file                        ##
##################################################################
# For each sample generate .bed file with columns: 
# chr, start, end, center, p_value vs Contorl
# in data/homer_peaks_processed/ directory.
# also generate summary file with number of peaks in each sample.
rule process_homer_peaks:
    input:
        peaks = "results/homer_peaks/{group}_{rep}.bed"
    output:
        "results/homer_peaks_processed/{group}_{rep}.bed"
    params:
        telomer_length = config['telomer_length']
    log:
        "logs/process_peaks/{group}_{rep}.log"
    shell:
        """
        python3 "scripts/process_peaks.py" \
        --input {input.peaks} \
        --out_dir results/homer_peaks_processed \
        -t {params.telomer_length} \
        2> {log}
        echo "{wildcards.group}_{wildcards.rep} peaks count" >> {log}
        wc -l < {output[0]} >> {log}
        """

##################################################################
##                    Merge replicates.                         ##
##################################################################
rule merge_peaks:
    input:
        A="results/homer_peaks_processed/{group}_A.bed",
        B="results/homer_peaks_processed/{group}_B.bed",
        C="results/homer_peaks_processed/{group}_C.bed"
    output:
        "results/homer_peaks_merged/{group}.bed"
    log:
        "logs/merge_peaks/{group}.log"
    shell:
        """
        python3 scripts/merge_peaks.py \
        -A {input.A} \
        -B {input.B} \
        -C {input.C} \
        --output {output[0]} \
        2> {log}
        echo "{wildcards.group} peaks count" >> {log}
        wc -l < {output[0]} >> {log}
        """
