configfile: "config/config.yaml"

##################################################################
##                  Specific Steps in Pipeline                  ##
##################################################################
#   Steps:
#   1) Upload data (if already exists - ask to replace or skip)
#   2) Convert BAM to SAM
#   3) Create TAG directory
#   4) HOMER peak calling
#   5) Process HOMER peaks
#   6) Merge peaks

##################################################################
##                  Functions & variables                       ##
##################################################################
import shutil
import glob
import os
import pandas as pd

bam_dir = glob.glob(f"{config['project']}/ChEC-Seq_Analysis-*/results/alignment/scer")[0]
bwig_dir = glob.glob(f"{config['project']}/ChEC-Seq_Analysis-*/results/bigwig")[0]
samplescsv = glob.glob(f"{config['project']}/ChEC-Seq_Analysis-*/config/samples.csv")[0]
df = pd.read_csv(samplescsv)
merged = df['merge_group'].tolist()
samples = df['sample'].tolist()
action = "R" if config['overwrite'] else "S"

def copy_files(in_dir, out_dir, file_format, action):
    # Create new output subdirectory
    os.makedirs(out_dir, exist_ok=True)
    # Check if input directory exists
    if not os.path.exists(in_dir):
        print(f"Warning: Input directory {in_dir} does not exist")
        return

    # Copy, replace or skip
    in_files = [f for f in os.listdir(in_dir) if f.endswith(file_format)]
    for f_name in in_files:
        dest_f = os.path.join(out_dir, f_name)
        if os.path.exists(dest_f):
            if action == 'R':
                shutil.copy2(os.path.join(in_dir, f_name), dest_f)
                print(f"Replaced: {f_name}")
            else:
                print(f"Skipped: {f_name}")
        else:
            shutil.copy2(os.path.join(in_dir, f_name), dest_f)
            print(f"Copied: {f_name}")

def bw2wig(in_dir, out_dir, action):
    # Create new output subdirectory
    os.makedirs(out_dir, exist_ok=True)
    # Check if input directory exists
    if not os.path.exists(in_dir):
        print(f"Warning: Input directory {in_dir} does not exist")
        return

    # Copy, replace or skip
    bw_files = [f for f in os.listdir(in_dir) if f.endswith(".bw")]
    for bw_name in bw_files:
        wig_name = os.path.splitext(bw_name)[0]+'.wig'
        wig_path = os.path.join(out_dir, wig_name)
        bw_path = os.path.join(in_dir, bw_name)
        if os.path.exists(wig_path):
            if action == 'R':
                shell(f"scripts/bigWigToWig {bw_path} {wig_path}")
                print(f"Replaced: {wig_name}")
            else:
                print(f"Skipped: {wig_name}")
        else:
            shell(f"scripts/bigWigToWig {bw_path} {wig_path}")
            print(f"Copied: {wig_name}")

##################################################################
##                          Rule all                            ##
##################################################################
rule all:
    input:
        expand("results/homer_peaks_merged/{group}.bed", group=merge_group)

##################################################################
##                        Upload data                           ##
##################################################################
def upload():
    print(f"Coping files from {config['project']}..")

    bam_out_dir = "data/bam/"
    bw_out_dir = "data/bigwig/"
    wig_out_dir = "data/wig/"

    # Create dir for data if do not already exist
    os.makedirs(bam_out_dir, exist_ok=True)
    os.makedirs(bw_out_dir, exist_ok=True)
    os.makedirs(wig_out_dir, exist_ok=True)

    # Copy bam and bigwig files from scratch
    # If files already exists - ask user replace (R) or skip (S) files
    copy_files(bam_dir, bam_out_dir, '.bam', action)
    copy_files(os.path.join(bwig_dir, 'cpm'), os.path.join(bw_out_dir, 'cpm'), '.bw', action)
    copy_files(os.path.join(bwig_dir, 'cpm_mean'), os.path.join(bw_out_dir, 'cpm_mean'), '.bw', action)
    copy_files(os.path.join(bwig_dir, 'spikein'), os.path.join(bw_out_dir, 'spikein'), '.bw', action)
    copy_files(os.path.join(bwig_dir, 'spikein_mean'), os.path.join(bw_out_dir, 'spikein_mean'), '.bw', action)

    # Generate wig files from bigwig
    bw2wig(os.path.join(bwig_dir, 'cpm'), os.path.join('data/wig', 'cpm'), action)
    bw2wig(os.path.join(bwig_dir, 'cpm_mean'), os.path.join('data/wig', 'cpm_mean'), action)
    bw2wig(os.path.join(bwig_dir, 'spikein'), os.path.join('data/wig', 'spikein'), action)
    bw2wig(os.path.join(bwig_dir, 'spikein_mean'), os.path.join('data/wig', 'spikein_mean'), action)

rule upload_data:
    output:
        bam_files = expand(
            "data/bam/{sample}.bam",
            sample=samples
        ),
        complete = touch("data/.upload_complete")
    log:
        "logs/upload_data.log"
    run:
        upload()
            
##################################################################
##                        BAM to SAM                            ##
##################################################################
rule bam2sam:
    input:
        bam = "data/bam/{sample}.bam",
    output:
        sam = "results/sam/{sample}.sam"
    log:
        "logs/bam_to_sam/{sample}.log"
    shell:
        """
        samtools view {input.bam} > {output.sam} 2> {log}
        """

##################################################################
##                    Create Tag directories                    ##
##################################################################
rule homer_tags:
    input:
        sam = "results/sam/{sample}.sam"
    output:
        tag_dir = directory("results/seq_tags/{sample}")
    params:
        keepAll = config["homer_params"]["keepAll"]
    log:
        "logs/make_tag/{sample}.log"
    shell:
        """
        echo "Creating TAG directory for {wildcards.sample}.."
        makeTagDirectory {output.tag_dir} {input.sam} -keepAll {params.keepAll} 2> {log}
        """

##################################################################
##                         Peak calling                         ##
##################################################################
rule peak_calling:
    input:
        tag_dir = "results/seq_tags/{sample}"
    output:
        homer_peaks = "results/homer_peaks/{sample}.bed"
    params:
        control = config["control_tags"],
        style = config["homer_params"]["style"],
        size = config["homer_params"]["size"],
        C = config["homer_params"]["C"],
        L = config["homer_params"]["L"],
        F = config["homer_params"]["F"]
    log:
        "logs/peak_calling/{sample}.log"
    shell:
        """
            findPeaks {input.tag_dir} \
                -style {params.style} \
                -size {params.size} \
                -i {params.control} \
                -o auto \
                -C {params.C} \
                -L {params.L} \
                -F {params.F} \
                2>> {log}
        
        # Homer generates files in tag_dir, copy it to corresponding peak directory
        cp {input.tag_dir}/peaks.txt {output.homer_peaks}
        echo "Called peaks for {wildcards.sample} and saved to {output.homer_peaks}" 
        """

##################################################################
##                    Process peaks file                        ##
##################################################################
# For each sample generate .bed file with columns: 
# chr, start, end, center, p_value vs Contorl
# in data/homer_peaks_processed/ directory.
# also generate summary file with number of peaks in each sample.
rule process_homer_peaks:
    input:
        peaks = "results/homer_peaks/{sample}.bed"
    output:
        processed_peaks = "results/homer_peaks_processed/{sample}.bed"
    params:
        telomer_length = config['telomer_length']
    log:
        "logs/process_peaks/{sample}.log"
    shell:
        """
        python3 "scripts/process_peaks.py" \
        --input {input.peaks} \
        --out_dir results/homer_peaks_processed \
        -t {params.telomer_length} \
        2> {log}
        """

##################################################################
##                    Merge replicates.                         ##
##################################################################
rule merge_peaks:
    input:
        expand("results/homer_peaks_processed/{group}_{rep}.bed", 
                                rep=['A', 'B', 'C'])
    output:
        "results/homer_peaks_merged/{group}.bed"
    log:
        "logs/merge_peaks/merge.log"
    shell:
        """
        python3 scripts/merge_peaks.py \
        -A results/homer_peaks_processed/{group}_A.bed \
        -B results/homer_peaks_processed/{group}_B.bed \
        -C results/homer_peaks_processed/{group}_C.bed \
        -output results/homer_peaks_merged/{group}.bed \
        2> {log}
        """