configfile: "config/config.yaml"

##################################################################
##                  Specific Steps in Pipeline                  ##
##################################################################
#   Steps:
#   1) Upload data (if already exists - ask to replace or skip)
#   2) Convert BAM to SAM
#   3) Create TAG directory
#   4) HOMER peak calling
#   5) Process HOMER peaks
#   6) Merge peaks

##################################################################
##                       Define functions                       ##
##################################################################
import shutil
import glob
import os

def check_duplic(in_dir, out_dir):
    in_files = [f for f in os.listdir(in_dir) if f.endswith(".bam")]
    out_files = [f for f in os.listdir(out_dir) if f.endswith(".bam")]
    common = set(in_files) & set(out_dir)
    if len(common) != 0:
        while True:
            response = input(f"Files {common} already exist. Replace (R) or Skip (S)? ").upper()
            if response in ['R', 'S']:
                return response
            print("Invalid input. Please enter 'R' for replace or 'S' for skip.")

def copy_files(in_dir, out_dir, file_format, action):
    # Create new output subdirectory
    os.makedirs(out_dir, exist_ok=True)
    # Check if input directory exists
    if not os.path.exists(in_dir):
        print(f"Warning: Input directory {in_dir} does not exist")
        return

    # Copy, replace or skip
    in_files = [f for f in os.listdir(in_dir) if f.endswith(file_format)]
    for f_name in in_files:
        dest_f = os.path.join(out_dir, f_name)
        if os.path.exists(dest_f):
            if action == 'R':
                shutil.copy2(os.path.join(in_dir, f_name), dest_f)
                print(f"Replaced: {f_name}")
            else:
                print(f"Skipped: {f_name}")
        else:
            shutil.copy2(os.path.join(in_dir, f_name), dest_f)
            print(f"Copied: {f_name}")

def bw2wig(in_dir, out_dir, action):
    # Create new output subdirectory
    os.makedirs(out_dir, exist_ok=True)
    # Check if input directory exists
    if not os.path.exists(in_dir):
        print(f"Warning: Input directory {in_dir} does not exist")
        return

    # Copy, replace or skip
    bw_files = [f for f in os.listdir(in_dir) if f.endswith(".bw")]
    for bw_name in bw_files:
        wig_name = os.path.splitext(bw_name)[0]+'.wig'
        wig_path = os.path.join(out_dir, wig_name)
        bw_path = os.path.join(in_dir, bw_name)
        if os.path.exists(wig_path):
            if action == 'R':
                shell(f"scripts/0_upload_data/bigWigToWig {bw_path} {wig_path}")
                print(f"Replaced: {wig_name}")
            else:
                print(f"Skipped: {wig_name}")
        else:
            shell(f"scripts/0_upload_data/bigWigToWig {bw_path} {wig_path}")
            print(f"Copied: {wig_name}")

##################################################################
##                        Upload data                           ##
##################################################################

# Upload data from scratch folder
rule upload_data:
    input: 
        bam_dir = lambda wildcards: f"{config["project"]}/ChEC-Seq_Analysis-*/results/alignment/scer",
        bwig_dir = lambda wildcards: f"{config["project"]}/ChEC-Seq_Analysis-*/results/bigwig"
    run:
        print(f"Coping files from {config["project"]}..")

        # Create dir for data if do not already exist
        bam_out_dir = "data/bam"
        bw_out_dir = "data/bigwig"
        wig_out_dir = "data/wig"
        os.makedirs("data/bam", exist_ok=True)
        os.makedirs(o"data/bigwig", exist_ok=True)
        os.makedirs("data/wig", exist_ok=True)

        # Ask user to skip or replace existing files
        if os.path.exists(bam_out_dir) and os.listdir(bam_out_dir):
            action = check_duplic(bam_dir, bam_out_dir)
        else:
            action = 'R'

        # Copy bam and bigwig files from scratch
        # If files already exists - ask user replace (R) or skip (S) files
        copy_files(bam_dir, bam_out_dir, '*.bam', action)
        copy_files(os.path.join(bwig_dir, 'cpm'), os.path.join(bw_out_dir, 'cpm'), '.bw', action)
        copy_files(os.path.join(bwig_dir, 'cpm_mean'), os.path.join(bw_out_dir, 'cpm_mean'), '.bw', action)
        copy_files(os.path.join(bwig_dir, 'spikein'), os.path.join(bw_out_dir, 'spikein'), '.bw', action)
        copy_files(os.path.join(bwig_dir, 'spikein_mean'), os.path.join(bw_out_dir, 'spikein_mean'), '.bw', action)

        # Generate wig files from bigwig
        bw2wig(os.path.join(bwig_dir, 'cpm'), os.path.join('data/wig', 'cpm'), action)
        bw2wig(os.path.join(bwig_dir, 'cpm_mean'), os.path.join('data/wig', 'cpm_mean'), action)
        bw2wig(os.path.join(bwig_dir, 'spikein'), os.path.join('data/wig', 'spikein'), action)
        bw2wig(os.path.join(bwig_dir, 'spikein_mean'), os.path.join('data/wig', 'spikein_mean'), action)
            
##################################################################
##                        BAM to SAM                            ##
##################################################################
rule bam2sam:
    input:
        bam = lambda wildcards: f{config["bam_dir"]/{wildcards.sample}.bam}
    output:
        sam = "results/sam/{sample}.sam"
    log:
        "logs/bam_to_sam/{sample}.log"
    run:
        if os.path.exists(output.sam):
            print(f"SAM file already exists {output.sam}, skipping..")
        else:
            print(f"Converting {sample} BAM file to SAM.."),
            shell("samtools view {input.bam} > {output.bam} 2> {log}")

##################################################################
##                    Create Tag directories                    ##
##################################################################
rule homer_tags:
    input:
        sam = "results/sam/{sample}.sam"
    output:
        tag_dir = directory("results/seq_tags/{sample}")
    params:
        keepAll = config["homer_params"]["keepAll"]
    log:
        "logs/make_tag/{sample}.log"
    run:
        if os.path.exists(output.tag_dir):
            print(f"Tag directory {output.tag_dir} already exists, skipping..")
        else:
            print(f"Creating TAG directory for {sample}.."),
            shell("makeTagDirectory {output.tag_dir} {input.sam} -keepAll {params.keepAll} 2> {log}")

##################################################################
##                         Peak calling                         ##
##################################################################
rule peak_calling:
    input:
        tag_dir = "results/seq_tags/{sample}",
        control = config["control_tags"]
    output:
        homer_peaks = "results/homer_peaks/{sample}.bed",
        summary = "results/homer_peaks/{sample}_summary.txt"
    params:
        style = config["homer_params"]["style"],
        size = config["homer_params"]["size"],
        C = config["homer_params"]["C"],
        L = config["homer_params"]["L"],
        F = config["homer_params"]["F"]
    log:
        "logs/peak_calling/{sample}.log"
    run:
        if os.path.exists(output.homer_peaks):
            print(f"Peak file {output.homer_peaks} already exists, skipping..")
        else:
            shell("""
                findPeaks {input.tag_dir} \
                    -style {params.style} \
                    -size {params.size} \
                    -i {input.control} \
                    -o auto \
                    -C {params.C} \
                    -L {params.L} \ 
                    -F {params.F} \
                    2>> {log}
            """)
            # Homer generates files in tag_dir, copy it to corresponding peak directory
            shell("cp {input.tag_dir}/peaks.txt {output.homer_peaks}")

            with open(output.summary, 'w') as f:
                f.write(f"Sample: {wildcards.sample}\n")
                f.write(f"Date: $(date)\n")
                f.write(f"Parameters: style={params.style}, size={params.size}, C={params.C}, L={params.L}, F={params.F}\n")
            
            print(f"Called peaks for {wildcards.sample} and saved to {output.homer_peaks}")

##################################################################
##                    Process peaks file                        ##
##################################################################
# For each sample generate .bed file with columns: chr, start, end, center, p_value vs Contorl in data/homer_peaks_processed/ directory.
# Also generate summary file with number of peaks in each sample.
rule process_homer_peaks:
    input:
        peaks = "results/homer_peaks/{sample}.bed"
    output:
        processed_peaks = "results/homer_peaks_processed/{sample}.processed.bed"
    params:
        script = "scripts/1_peak_calling/homer_peaks_processing.py"
    log:
        "logs/process_peaks/{sample}.log"
    run:
        shell("python3 {params.script} --input {input.peaks} --output {output.processed_peaks} -f {filter_telomers} -t {telomer_length} 2> {log}")

##################################################################
##                    Merge replicates.                         ##
##################################################################
rule merge_peaks:
    input:
        processed_peaks_dir = "results/homer_peaks_processed"
    output:
        merged_peaks_dir = "results/merged_peaks"
    params:
        script = "scripts/1_peak_calling/merge_peaks.py"
    log:
        "logs/process_peaks/{sample}.log"
    run:
        shell("""
            python3 {params.script} \
            {input.processed_peaks_dir} \ 
            {output.merged_peaks_dir}
        """)