# ChEC-seq_Peak_Calling_Merging pipeline configuration

# You for sure want to change project_dir path
project: "/s/donczew-lab/RDHTSP49"
overwrite: true

control_tags: "config/control_tags/RDY45_A"
telomer_length: 1000

# HOMER parameters
homer_params:
  keepAll: true
  style: "factor"
  size: 150
  C: 0
  L: 3
  F: 3